### ISSUE TITLE
How can I use this ? 

### ISSUE THREAD

**Issue by anasvn** [SpitfireSatya/tslint-html-report#1]
The mentioned documentation is not helping me.
Where I should include `tslintHtmlReport()` function ?

**Comment by SpitfireSatya** [comment]
Well you can invoke tslintHtmlReport() in any JS file.

If you want to run the script through npm, you can create a file called lint.js and invoke the function in that with the proper config. And then add it to your package.json as:
```
{
    "scripts": {
        "lint": "node lint.js"
    }
}
```

Or if you use gulp in your project, You can create a gulp task for it:
```
gulp('lint', () => {
    const config = {};
    tslintHtmlReport(config);
});
```
And invoke gulp lint.

Also, all paths in the config are relative to the root of your project.

Hope this helps.

Cheers,
Spitfire
