### ISSUE TITLE
breakonError: true doesnt produce html report

### ISSUE THREAD

**Issue by herebebogans** [SpitfireSatya/tslint-html-report#2]
I'm not sure if this in the intended effect but setting

`breakonError: true` 

only produces the tslint json output if there are lint errors.

I *think* the shell return code from 

`const result = npmRun.execSync('tslint' + cliArguments, { cwd: __dirname });` 

needs to be swallowed and then propogated to gulp for this to work?

**Comment by SpitfireSatya** [comment]
Thanks for reporting the issue. I'll have a look into it asap.
I know there are a few other things missing as well (such as an option to exclude files). 

I've been a bit busy elsewhere lately, but i'll patch it up soon.

**Comment by SpitfireSatya** [comment]
@herebebogans The issue has been fixed. Please try it out and let me know so that we can close this issue.

Cheers,
Spitfire

**Comment by herebebogans** [comment]
Thanks! .. Fixed ..
