### ISSUE TITLE
Total lint issues found is always 0

### ISSUE THREAD

**Issue by obriankevin11** [SpitfireSatya/tslint-html-report#7]
Hi,

I have bunch of tslint warnings but when I run my command I always get this: 

```
Tslint report written to JSON
Reading json file...
File read complete.
Mapping data...
Data mapping complete.
Writing data...
Data write complete.

Total lint issues found:  0
TSLint html report generated and written to file
```

My paths to json files, source files, output path for the report are correct.
My tslint.json "extends": ["tslint:recommended"] and has some custom "rules": {...}
`tslint -p ./`reports lots of errors.

Any idea?

Thank you!

**Comment by teresitaya** [comment]
The same bug happend to me

**Comment by SpitfireSatya** [comment]
Hi,

I have personally used this with "extends": ["tslint:recommended"] and custom rules as well, so that should not be an issue.
Please share the config you used along with this.

My first instinct is that the "exclude" property in the config might be set to "src/**/*.ts". (just a wild guess)

Sorry for the late response, I somehow didn't get a notification for this issue.

Cheers,
Spitfire

**Comment by teresitaya** [comment]
Hi, these is my tslint.json configuration. I have not exlude files. Thanks

{
	"rulesDirectory": [
		"node_modules/codelyzer"
  ],
  "extends": ["tslint:recommended"],
  "defaultSeverity":"warning",
	"rules": {
    "align": [true, "parameters", "statements","elements","members"],
    "arrow-return-shorthand": true,
    "no-duplicate-imports": true,
		"callable-types": true,
    "no-duplicate-variable": [true, "check-parameters"],
    "no-magic-numbers": true,
    "class-name": true,
    "max-classes-per-file": [true, 1],
    "ordered-imports": true,
    "cyclomatic-complexity": true,
		"comment-format": [
			true,
			"check-space"
		],
		"curly": true,
		"eofline": true,
		"forin": true,
		"import-blacklist": [
			true,
			"rxjs",
			"rxjs/Rx"
		],
		"import-spacing": true,
		"indent": [
			true,
			"spaces"
		],
		"interface-over-type-literal": true,
		"label-position": true,
		"max-line-length": [
			true,
			140
		],
		"member-access": false,
		"member-ordering": [
			true,
			{
				"order": [
					"static-field",
					"instance-field",
					"static-method",
					"instance-method"
				]
			}
		],
		"no-arg": true,
		"no-bitwise": true,
		"no-console": [
			true,
			"debug",
			"info",
			"time",
			"timeEnd",
      "trace",
      "log"
		],
		"no-construct": true,
		"no-debugger": true,
		"no-duplicate-super": true,
    "no-empty": [true, "allow-empty-catch"],
    "max-file-line-count": [true, 400],
		"no-empty-interface": true,
		"no-eval": true,
		"no-inferrable-types": [
			true,
			"ignore-params"
		],
		"no-misused-new": true,
		"no-non-null-assertion": true,
		"no-shadowed-variable": true,
		"no-string-literal": false,
		"no-string-throw": true,
		"no-switch-case-fall-through": true,
		"no-trailing-whitespace": true,
		"no-unnecessary-initializer": true,
		"no-unused-expression": true,
		"no-var-keyword": true,
		"object-literal-sort-keys": false,
		"one-line": [
			true,
			"check-open-brace",
			"check-catch",
			"check-else",
			"check-whitespace"
		],
		"prefer-const": true,
		"quotemark": [
			true,
			"single"
		],
		"radix": true,
		"semicolon": [
			true,
			"always"
		],
		"triple-equals": [
			true,
			"allow-null-check"
		],
		"typedef-whitespace": [
			true,
			{
				"call-signature": "nospace",
				"index-signature": "nospace",
				"parameter": "nospace",
				"property-declaration": "nospace",
				"variable-declaration": "nospace"
			}
		],
		"unified-signatures": true,
		"variable-name": false,
		"whitespace": [
			true,
			"check-branch",
			"check-decl",
			"check-operator",
			"check-separator",
			"check-type"
		],
		"directive-selector": [
			true,
			"attribute",
			"app",
			"camelCase"
		],
		"component-selector": [
			true,
			"element",
			"app",
			"kebab-case"
		],
		"no-output-on-prefix": true,
		"use-input-property-decorator": true,
		"use-output-property-decorator": true,
		"use-host-property-decorator": true,
		"no-input-rename": true,
		"no-output-rename": true,
		"use-life-cycle-interface": true,
		"use-pipe-transform-interface": true,
		"component-class-suffix": true,
    "directive-class-suffix": true,
    "file-name-casing": [true, "kebab-case"]
	},
	"jsRules": {
    "file-name-casing": [true, "kebab-case"],
    "align": [true, "parameters", "statements","elements","members"],
		"arrow-return-shorthand": true,
		"class-name": true,
		"comment-format": [
			true,
			"check-space"
		],
		"curly": true,
		"eofline": true,
		"forin": true,
		"import-blacklist": [
			true,
			"rxjs",
			"rxjs/Rx"
		],
		"import-spacing": true,
		"indent": [
			true,
			"spaces"
		],
		"label-position": true,
		"max-line-length": [
			true,
			140
		],
		"member-access": false,
		"member-ordering": [
			true,
			{
				"order": [
					"static-field",
					"instance-field",
					"static-method",
					"instance-method"
				]
			}
		],
    "no-arg": true,
    "no-duplicate-variable": [true, "check-parameters"],
		"no-bitwise": true,
		"no-console": [
			true,
			"debug",
			"info",
			"time",
			"timeEnd",
      "trace",
      "log"
		],
		"no-construct": true,
		"no-debugger": true,
		"no-empty": [true, "allow-empty-catch"],
		"no-eval": true,
		"no-shadowed-variable": true,
		"no-string-literal": false,
		"no-string-throw": true,
		"no-switch-case-fall-through": true,
		"no-trailing-whitespace": true,
		"no-unnecessary-initializer": true,
		"no-unused-expression": true,
     "no-duplicate-super": true,
     "max-file-line-count": [true, 400],
		"object-literal-sort-keys": false,
		"one-line": [
			true,
			"check-open-brace",
			"check-catch",
			"check-else",
			"check-whitespace"
		],
		"prefer-const": true,
		"quotemark": [
			true,
			"single"
		],
		"radix": true,
		"semicolon": [
			true,
			"always"
		],
		"triple-equals": [
			true,
			"allow-null-check"
		],
		"variable-name": false,
		"whitespace": [
			true,
			"check-branch",
			"check-decl",
			"check-operator",
			"check-separator",
			"check-type"
		]
	}
}

**Comment by SpitfireSatya** [comment]
I meant the config you pass to tslintHtmlReporter, not the tslint.json

```
const tslintHtmlReport = require('tslint-html-report');

tslintHtmlReport({/*config*/}, callback);
```

The default is this:
```
{
  tslint: 'node_modules/tslint-html-report/tslint.json', // path to tslint.json
  srcFiles: 'src/**/*.ts', // files to lint
  outDir: 'reports/tslint-html-report', // output folder to write the report to
  html: 'tslint-report.html', // name of the html report generated
  exclude: ['src/**/*.ts'], // Files/patterns to exclude
  breakOnError: false, // Should it throw an error in tslint errors are found
  typeCheck: true, // enable type checking. requires tsconfig.json
  tsconfig: 'tsconfig.json' // path to tsconfig.json
}
```

**Comment by teresitaya** [comment]
Sorry, this is:
gulp.task('buildReport', function() {
      tslintHtmlReport({
      tslint: 'tslint.json',
      srcFiles: './SPA/modules/**/*.ts?(x)', 
      outDir: 'reports/tslint-html-report',
      html: 'tslint-report.html',
      breakOnError: false,
      typeCheck: true,
      tsconfig: 'tsconfig.json'
    });
});

**Comment by teresitaya** [comment]
Yes is correct, when I run the lint task, show the lint errors, but when I run buildReport, this is the output:
Config used for generation of report:
Path to tslint.json:  C:\Repos\WebApp\tslint.json
Path to tsconfig.json:  C:\Repos\WebApp\tsconfig.json
Source files to be linted:  C:\Repos\WebApp\SPA\modules\**\*.ts
Output path for HTML report:  C:\Repos\WebApp\reports\tslint-html-report\tslint-report.html
Generating TSlint report.

Tslint report written to JSON
Reading json file...
File read complete.
Mapping data...
Data mapping complete.
Writing data...
Data write complete.

Total lint issues found:  0
TSLint html report generated and written to file

**Comment by SpitfireSatya** [comment]
Is this a typo: 
Source files to be linted: C:\Repos\WebApp\SPA\modules***.ts?

It should be: 
Source files to be linted: C:\Repos\WebApp\SPA\modules\**\*.ts?(x)

**Comment by teresitaya** [comment]
No, is not a typo, I updated the configuration to  srcFiles: './SPA/modules/**/*.ts', testing the 2 variants and nothing. Sorry for so much problems

**Comment by SpitfireSatya** [comment]
Ok I guess only option in that case is a repo to reproduce this issue.
Please set one up with configs similar to yours and I'll try and debug on it.

Sorry I can't help much at this point. Seeing this issue for the first time.

**Comment by teresitaya** [comment]
Ok, thanks. I let you know
